### ISSUE TITLE
Searching for "String" finds "StaticString" first

### ISSUE THREAD

**Issue by kballard** [SwiftDocOrg/swiftdoc.org#13]
The search results sort purely alphabetically. This means that searching for "String" provides "StaticString" as the first result, even though the needle only matches at the end. It should prioritize earlier matches and only use alphabetic for matches that start at the same index.

**Comment by natecook1000** [comment]
Gah, this drives me nuts every time. Fix forthcoming!

**Comment by natecook1000** [comment]
Addressed by c9f3914734b47d850075fcdbb359ec3329f8585d. @kballard, what do you think?

**Comment by kballard** [comment]
Searching for "String" now gives me `String` first, but I am curious why you're explicitly special-casing prefix matches? If I search for "ring", I get `_CocoaStringType`, `_NSStringCoreType`, `_StringElementType`, and `StaticString` before `String`. It feels oddly inconsistent. The only benefit I can see to this approach is searching for a suffix like "Generator" then yields the various generator types in alphabetic order. But I don't think that's a worthwhile tradeoff.

In fact, if I search for "Int", I get a bunch of results like `ClosedInterval`, `COpaquePointer`, `ManagedBufferPointer`, `println`, etc before I get `UInt`.

I'm also curious what happened to the underlining. As I recall, the search results before were underlining the portion of the result that matched the search string, which I liked.

**Comment by natecook1000** [comment]
Great points. I optimized for `String` since that has so often been my frustration point, and simply missed the remainder of your original issue text. Sorting is now by the location of the search term first, then alphabetically. A much better result all around.

The underlines are now back! As part of switch to manual sorting, I got rid of the grouping by type, protocol, etc., which never truly made sense. Adding that information inline overrode the default result formatting, which included that underline.

Thanks for your feedback on this — better search result for all! :tada:
